import type { Metadata } from "next";
import { Prata, Yeseva_One } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers/Providers";
import AppBar from "@/components/AppBar/AppBar";
import Footer from "@/components/Footer/Footer";

const prata = Prata({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prata.className}>
        <AppBar />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
