import type { Metadata } from "next";
import { Prata } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { Providers } from "@/app/ui/Providers";

import Footer from "./ui/Footer";
import AppBar from "./ui/AppBar";

import "./globals.css";

const prata = Prata({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prata.className}>
        <AppBar />
        <Providers>{children}</Providers>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
